Entry.create!( name: 'Borby' )
Entry.create!( name: 'Aticus' )
Entry.create!( name: 'Charles Barkley' )
Entry.create!( name: 'Stone Phillips' )
Entry.create!( name: 'JRR' )
Entry.create!( name: 'Mel' )
Entry.create!( name: 'Reamer' )
Entry.create!( name: 'J.Biebs' )
Entry.create!( name: 'Jackson' )